default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: ksenija13
  pool: 5

development:
  <<: *default
  database: Trendy_v2

test:
  <<: *default
  database: Trendy_v2_test

production:
  <<: *default
  database: Trendy_v2_production
  username: reddit_clone
  password: <%= ENV['REDDIT_CLONE_DATABASE_PASSWORD'] %>
